<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zzzp005_imageslider.aspx.cs" Inherits="webapp.Forms.zzz.zzzp005_imageslider" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <dx:ASPxRoundPanel ID="rpl_master" runat="server" ShowCollapseButton="true" Theme="BlackGlass" Width="100%">
                <PanelCollection>
<dx:PanelContent runat="server">
    <dx:ASPxImageSlider ID="igs_master" runat="server" Height="200px" ImageSourceFolder="~/photos" ShowNavigationBar="False" Width="400px">
        <SettingsSlideShow AutoPlay="True" PausePlayingWhenMouseOver="True" PlayPauseButtonVisibility="OnMouseOver" />
        <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
    </dx:ASPxImageSlider>
                    </dx:PanelContent>
</PanelCollection>
            </dx:ASPxRoundPanel>
        </div>
    </form>
</body>
</html>
